main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('category/<int:category_id>/page/<int:page_num>/',  views.category, name='page'),
    path('object/<int:object_id>', views.object, name="object"),
    path('page/<int:page_id>/', views.page, name="page"),
    path('search', views.search, name="search"),
]

webcatcms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models

from django.core import validators
from django.conf import settings
from filer.fields.image import FilerImageField
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Setting(models.Model):
    title = models.CharField(
        "Заголовок",
        max_length=30)

    base_url = models.URLField(
        "Головне посилання",
        max_length=50,
        validators=[validators.URLValidator(schemes=['http', 'https'])],)

    meta_description = models.TextField(
        "Мета опис",
        max_length=100,
        null=True,
        blank=True)

    work_schedule = models.CharField(
        "Графік роботи",
        max_length=30,
        null=True,
        blank=True)

    phone_1 = models.CharField(
        "Телефон №1",
        max_length=30,
        null=True,
        blank=True,
        validators=[validators.RegexValidator(regex='^[0-9]{10}$')],
        error_messages={'invalid': 'некоректний формат телефону'})

    phone_2 = models.CharField(
        "Телефон №2",
        max_length=30,
        null=True,
        blank=True,
        validators=[validators.RegexValidator(regex='^[0-9]{10}$')],
        error_messages={'invalid': 'некоректний формат телефону'})

    phone_3 = models.CharField(
        "Телефон №3",
        max_length=30,
        null=True,
        blank=True,
        validators=[validators.RegexValidator(regex='^[0-9]{10}$')],
        error_messages={'invalid': 'некоректний формат телефону'})

    phone_4 = models.CharField(
        "Телефон №4",
        max_length=30,
        null=True,
        blank=True,
        validators=[validators.RegexValidator(regex='^[0-9]{10}$')],
        error_messages={'invalid': 'некоректний формат телефону'})

    email_1 = models.CharField(
        "Почта №1",
        max_length=30,
        null=True,
        blank=True,
        validators=[validators.validate_email],
        error_messages={'invalid': 'некоректний формат скриньки'})

    email_2 = models.CharField(
        "Почта №2",
        max_length=30,
        null=True,
        blank=True,
        validators=[validators.validate_email],
        error_messages={'invalid': 'некоректний формат скриньки'})

    link_facebook = models.CharField(
        "Посилання Facebook",
        max_length=100,
        null=True,
        blank=True)

    link_instagram = models.CharField(
        "Посилання Instagram",
        max_length=100,
        null=True,
        blank=True)

    link_telegram = models.CharField(
        "Посилання Telegram",
        max_length=50,
        null=True,
        blank=True)

    site_image = FilerImageField(
        null=True,
        blank=True,
        related_name="site_image",
        on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Налаштування"
        verbose_name_plural = "Налаштування"

    def getSettings(self):

        settings = Setting.objects.get(id=1)

        def phone_split(x):
            if x[0:3] in ["039", "067", "068", "096", "097", "098"]:
                logo = "kyivstar.png"
            elif x[0:3] in ["050", "066", "095", "099"]:
                logo = "vodafone.png"
            elif x[0:3] in ["063", "073", "093"]:
                logo = "lifecell.png"
            else:
                logo = ''
            return {'phone': '-'.join([x[0:3], x[3:6], x[6:8], x[8:]]), 'logo': logo}

        settings.phone_1 = phone_split(settings.phone_1)
        settings.phone_2 = phone_split(settings.phone_2)
        settings.phone_3 = phone_split(settings.phone_3)
        settings.phone_4 = phone_split(settings.phone_4)

        return settings


class Locality(models.Model):

    name = models.CharField(
        "Назва",
        max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Населенный пункт"
        verbose_name_plural = "Населенні пункти:"


class Area(models.Model):

    name = models.CharField(
        "Назва",
        max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Район/Массив"
        verbose_name_plural = "Райони/Массиви"


class Street(models.Model):

    name = models.CharField(
        "Назва",
        max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Вулиця"
        verbose_name_plural = "Вулиці"


class Room(models.Model):

    name = models.CharField(
        "Назва",
        max_length=30,
        blank=True,
        null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Кількість кімнат"
        verbose_name_plural = "Кількість кімнат"


class Storey(models.Model):

    name = models.CharField(
        "Назва",
        max_length=30,
        blank=True,
        null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Поверховість"
        verbose_name_plural = "Поверховість"


class Currency(models.Model):

    name = models.CharField(
        "Назва",
        max_length=30)

    sign = models.CharField(
        "Знак",
        blank=True,
        null=True,
        max_length=1)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Валюта"
        verbose_name_plural = "Валюти"


class Category(models.Model):
    title = models.CharField(
        "Назва",
        max_length=30)

    description = RichTextUploadingField("Опис")
    image = FilerImageField(
        null=True,
        blank=True,
        related_name="image",
        on_delete=models.SET_NULL)

    meta_description = models.TextField(
        "Опис",
        max_length=100,
        null=True,
        blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"


class ObjectType(models.Model):
    name = models.CharField(
        "Назва",
        max_length=30
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тип Об'єкту"
        verbose_name_plural = "Типи Об'єктів"


def get_currency():
    default_currency = Currency.objects.get(name="Гривня")
    return default_currency.id


class ObjectProperty(models.Model):

    category_object = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        verbose_name="Категорія")

    object_type = models.ForeignKey(
        ObjectType,
        on_delete=models.PROTECT,
        verbose_name="Тип Об'єкту")

    title = models.CharField(
        "Назва",
        max_length=70)

    image = FilerImageField(
        verbose_name="Головне зображення",
        null=True,
        blank=True,
        related_name="image_object_total",
        on_delete=models.SET_NULL)

    description = RichTextUploadingField("Опис")

    meta_description = models.TextField(
        "Мета опис",
        max_length=160,
        null=True,
        blank=True)

    cad_num = models.CharField(
        "Кадастровий номер",
        max_length=30,
        null=True,
        blank=True
    )

    locality = models.ForeignKey(
        Locality,
        on_delete=models.PROTECT,
        verbose_name="Населенный пункт")

    area = models.ForeignKey(
        Area,
        on_delete=models.PROTECT,
        verbose_name="Район/Массив")

    street = models.ForeignKey(
        Street,
        on_delete=models.PROTECT,
        verbose_name="Вулиця")

    rooms = models.ForeignKey(
        Room,
        on_delete=models.PROTECT,
        verbose_name="Кількість кімнат",
        null=True,
        blank=True)

    total_space = models.IntegerField(
        "Загальна площа",
        null=True,
        blank=True)

    living_space = models.IntegerField(
        "Житлова площа",
        null=True,
        blank=True)

    kitchen_space = models.IntegerField(
        "Кухня площа",
        null=True,
        blank=True)

    height = models.FloatField(
        "Висота стелі",
        null=True,
        blank=True)

    floor = models.IntegerField(
        "Поверх",
        null=True,
        blank=True)

    storeys = models.ForeignKey(
        Storey,
        on_delete=models.PROTECT,
        verbose_name="Поверховість",
        null=True,
        blank=True
    )

    price = models.IntegerField("Ціна")

    currency = models.ForeignKey(
        Currency,
        on_delete=models.PROTECT,
        default=get_currency,
        verbose_name="Валюта")

    published = models.DateField(
        "Створено",
        auto_now_add=True,
        db_index=True)

    recommended = models.BooleanField(
        "Рекомендований",
        default=False)

    status = models.BooleanField(
        "Статус",
        default=True)

    def __str__(self):
        return self.title
    """
    @staticmethod
    def get_object_types(name):

        return (
            'Квартира',
            'Будинок',
            'Земельна ділянка',
            'Дачний масив',
            'Комерційна нерухомість')
    """
    class Meta:
        verbose_name = "Об'єкт"
        verbose_name_plural = "Об'єкти"
        ordering = ['-published']


class ObjectPropertyImage(models.Model):

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = "Зображення"
        verbose_name_plural = "Додаткові зображення"

    image = FilerImageField(
        null=True,
        blank=True,
        related_name="image_object",
        on_delete=models.SET_NULL)

    object_property = models.ForeignKey(
        ObjectProperty,
        related_name="images",
        on_delete=models.CASCADE,
        verbose_name="Зображення")


class Page(models.Model):
    title = models.CharField(
        "Назва",
        max_length=70)

    image = FilerImageField(
        verbose_name="Головне зображення",
        null=True,
        blank=True,
        related_name="image_page_total",
        on_delete=models.SET_NULL)

main/views.py
from django.http import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.db.models import Q
from .models import *
from django.core.cache import cache


def custom_page_not_found_view(request, exception):

    return render(request, "main/404.html", {})


def index(request):

    recommended = cache.get('recommended')
    if not recommended:
        recommended = ObjectProperty.objects.filter(recommended=True).select_related('image')
        cache.set('recommended', recommended, 3600)

    return render(request, 'main/index.html', {'recommended': recommended})


def category(request, category_id, page_num=1):

    category = Category.objects.get(id=category_id)

    objects = category.objectproperty_set.order_by('id')

    context = {'category': category}

    paginator = Paginator(objects, 6)

    try:
        context['objects'] = paginator.get_page(page_num)
    except PageNotAnInteger:
        context['objects'] = paginator.page(1)
    except EmptyPage:
        context['objects'] = paginator.page(paginator.num_pages)

    return render(request, 'main/objects.html', context)


def object(request, object_id):

    args = ['image', 'locality', 'category_object', 'street', 'area', 'rooms', 'storeys', 'currency']

    obj = ObjectProperty.objects.select_related(*args).get(id=object_id)

    context = dict()

    kwargs = {'object_type': obj.object_type, 'category_object': obj.category_object}

    context['interested'] = ObjectProperty.objects.exclude(pk=obj.id).select_related('image').filter(**kwargs)

    if obj.images.exists():

        context['images'] = obj.images.select_related('image').all()
        context['arrowsNav'] = 'true'

    else:
        context['arrowsNav'] = 'false'

    context['object'] = obj

    return render(request, 'main/object.html', context)


def page(request, page_id):

    p = Page.objects.get(id=page_id)
    context = dict()
    context['page'] = p
    return render(request, 'main/page.html', context)


def search(request, page_num=1):

    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':

        selected = request.read().decode('utf-8')

        if int(selected.split('=')[1]) == 4:
            response = JsonResponse({'fields': "block"})
        else:
            response = JsonResponse({'fields': "unblock"})
        return HttpResponse(response, content_type='application/json')

    if request.POST:
        query = QueryDict(request.readline())
        kwargs = dict()
        if int(query['category']):
            kwargs.update({'category_object_id': query['category']})

        if int(query['object_type']):
            kwargs.update({'object_type_id': query['object_type']})

        if int(query['locality']):
            kwargs.update({'locality_id': query['locality']})

        if int(query['storeys']):
            kwargs.update({'storeys_id': query['storeys']})

        if int(query['rooms']):
            kwargs.update({'rooms_id': query['rooms']})

        if int(query['currency']):
            kwargs.update({'currency_id': query['currency']})

        kwargs.update({'price__range': query['price'].split(';')})

        args = ['image', 'currency']

        objects = ObjectProperty.objects.filter(**kwargs).select_related(*args)

        context = dict()

        paginator = Paginator(objects, 6)

        try:
            context['objects'] = paginator.get_page(page_num)
        except PageNotAnInteger:
            context['objects'] = paginator.page(1)
        except EmptyPage:
            context['objects'] = paginator.page(paginator.num_pages)

        if objects:
            return render(request, 'main/objects.html', context)
        else:
            return render(request, 'main/object_not_found.html', context)

templates/main/index.html
{% extends "main/base.html" %}
{% load static %}
{% load cache %}
{% block title %}{{settings.title}}{% endblock %}
{% block meta_description %}{{settings.meta_description}}{% endblock %}
{% block og_title %}{{settings.title}}{% endblock %}
{% block site_name %}{{settings.title}}{% endblock %}
{% block base_url %}{{base_url}}{% endblock %}
{% block og_logo %}{{base_url}}/static/logo.png{% endblock %}
{% block og_description %}{{settings.meta_description}}{% endblock %}
{% block content %}
<!-- image site -->
    <div class="hero-wrap js-fullheight" style="background-image: url('{{settings.site_image.url}}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true"></div>
      </div>
    </div>
<!-- END -->
<!-- search -->
    <section class="ftco-section ftco-book ftco-no-pt ftco-no-pb">
      <div class="container">
        <div class="row justify-content-end">
          <div class="col-lg-4">
            <form action="{% url 'main:search' %}"  method="post" class="appointment-form">
              {% csrf_token %}
              {% cache 3600 search %}
              <!--<h3 class="mb-3">Пошук нерухомості</h3>-->
              <div class="row">
                <div class="col-md-12">
                   <div class="form-group">
                    <div class="form-field">
                      <div class="select-wrap">
                        <div class="icon"><span class="fa fa-chevron-down"></span></div>
                        <select name="category" id="category" class="form-control">
                          <option value="0">Категорія</option>
                          {% if categories %}
                              {% for category in categories %}
                                  <option  value="{{ category.id }}">{{ category }}</option>
                              {% endfor %}
                          {% endif %}
                        </select>
                      </div>
                    </div>
                  </div>
                   <div class="form-group">
                    <div class="form-field">
                      <div class="select-wrap">
                        <div class="icon"><span class="fa fa-chevron-down"></span></div>
                        <select name="object_type" id="object_type" class="form-control">
                          <option value="0">Тип Об'єкту</option>
                          {% if object_type %}
                              {% for type in object_type %}
                                  <option  value="{{ type.id }}">{{ type }}</option>
                              {% endfor %}
                          {% endif %}
                        </select>
                      </div>
                    </div>
                  </div>
                   <div class="form-group">
                    <div class="form-field">
                      <div class="select-wrap">
                        <div class="icon"><span class="fa fa-chevron-down"></span></div>
                        <select name="locality" id="locality" class="form-control">
                          <option value="0">Населенный пункт</option>
                          {% if locality %}
                              {% for location in locality %}
                                  <option  value="{{ location.id }}">{{ location }}</option>
                              {% endfor %}
                          {% endif %}
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <div class="form-field">
                      <div class="select-wrap">
                        <div class="icon"><span class="fa fa-chevron-down"></span></div>
                        <select name="storeys" id="storeys" class="form-control">
                          <option value="0">Поверховість</option>
                            {% if storeys %}
                              {% for storey in storeys %}
                                  <option  value="{{ storey.id }}">{{ storey }}</option>
                              {% endfor %}
                          {% endif %}
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <div class="form-field">
                      <div class="select-wrap">
                        <div class="icon"><span class="fa fa-chevron-down"></span></div>
                        <select name="rooms" id="rooms" class="form-control">
                          <option value="0">Кількість кімнат</option>
                          {% if rooms %}
                              {% for room in rooms %}
                                  <option  value="{{ room.id }}">{{ room }}</option>
                              {% endfor %}
                          {% endif %}
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
              {% if currency %}
                  <label style="display: none"><input type="radio" value="0" name="currency"  checked="checked" hidden/></label>
                  {% for cur in currency %}
                      <div class="col-md-4 col-4">
                          <div class="form-group">
                            <div class="form-field">
                              <label class="cur" for="{{ cur.id }}"><input type="radio" value="{{ cur.id }}" name="currency" id="{{ cur.id }}"  hidden/>{{ cur }}</label>
                            </div>
                          </div>
                        </div>
                  {% endfor %}
              {% endif %}

              <div class="col-md-12">
                  <div class="form-group">
                    <input id="price" type="text" name="price" value="" />
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <input type="submit" value="Знайти" class="btn btn-primary py-3 px-4">
                  </div>
                </div>
              </div>
              {% endcache %}
            </form>
          </div>
        </div>
      </div>
    </section>
<!-- END -->
<!-- Categories -->
    <section class="ftco-section ftco-services bg-light">
    	<div class="container">
    		<div class="row">
        {% for category in categories %}
          <div class="col-md-4 d-flex services align-self-stretch px-4 ftco-animate">
            <div class="d-block services-wrap text-center">
            <div class="hovereffect">
                <img class="img-responsive" src="{{category.image.url}}" alt="">
                <div class="overlay">
                   <h2>{{ category.title }}</h2>
                   <a class="info" href="{% url 'main:category' category.id %}">Дивитись</a>
                </div>
            </div>
          </div>
        </div>
        {% endfor %}
        </div>
    	</div>
    </section>
<!-- END Categories-->
<!-- slider recommended objects -->
<section class="ftco-section testimony-section bg-light">
  <div class="container">
    <div class="row justify-content-center pb-5 mb-3">
      <div class="col-md-12 heading-section text-center ftco-animate">
        <h3>Нерухомість онлайн РЕКОМЕНДУЄ</h3>
      </div>
    </div>
    <div class="row ftco-animate">
      <div class="col-md-12">
        <div class="carousel-testimony owl-carousel">

          {% for r in recommended %}
          <div class="item ">
            <div class="testimony-wrap d-flex">
            <div class="hovereffect">
                <img class="img-responsive" src="{{r.image.url}}" alt="">
                <p>{{r.title}}</p>
                <div class="overlay">
                   <a class="info" href="{% url 'main:object' r.id %}">Дивитись</a>
                </div>
            </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
<!-- END -->
{% endblock %}

templates/main/object_not_found.html
{% extends "main/base.html" %}
{% load static %}
{% load thumbnail %}
{% block title %}{{object.title}}{% endblock %}
{% block meta_description %}{{object.meta_description}}{% endblock %}
{% block og_title %}{{object.title}}{% endblock %}
{% block site_name %}{{object.title}}{% endblock %}
{% block base_url %}{{base_url}}{% endblock %}
{% block og_logo %}{{base_url}}static/logo.png{% endblock %}
{% block og_description %}{{object.meta_description}}{% endblock %}
{% block content %}

<section class="object_not_found">
  <div class="container">
    <div class="row">
    <div class="col-sm-12 ">
    <div class="col-sm-10 col-sm-offset-1  text-center">
    <div class="contant_box_404">
    <h3 class="h2">Жодного об'єкту не знайдено :( </h3>

    <p>Спробуйте пошук за іншими критеріями !</p>

    <a href="{{base_url}}" class="link_404">На говолну</a>
  </div>
    </div>
    </div>
    </div>
  </div>
</section>

{% endblock %}
{% block js %}

{% endblock %}

templates/main/objects.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}{{category.title}}{% endblock %}
{% block meta_description %}{{settings.meta_description}}{% endblock %}
{% block og_title %}{{category.title}}{% endblock %}
{% block site_name %}{{category.title}}{% endblock %}
{% block base_url %}{{base_url}}{% endblock %}
{% block og_logo %}{{base_url}}static/logo.png{% endblock %}
{% block og_description %}{{settings.meta_description}}{% endblock %}
{% block content %}
<section class="ftco-section bg-light">
  <div class="container">
    <div class="row justify-content-center pb-5 mb-3">
      <div class="col-md-12 heading-section text-center ftco-animate">
        <h3>{{category_objects.title}}</h3>
      </div>
    </div>
    <div class="row d-flex">
       {% for object in objects %}
      <div class="col-md-4 p-4 d-flex ftco-animate">
        <div class="blog-entry align-self-stretch">
          <a href="{% url 'main:object' object.id %}" class="block-20 rounded" style="background-image: url({{object.image.url}});">
          </a>
          <div class="text text-center">
            <h3 class="heading"><a href="{% url 'main:object' object.id %}">{{object.title}}</a></h3>
            <div class="meta mb-2">
              <div class="price">Ціна: <span>{{object.price}} {{ object.currency.sign }}</span></div>
            </div>
          </div>
        </div>
      </div>
     {% endfor %}
    </div>
    {% if objects.paginator.num_pages >= 2 %}
    <div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                {% if objects.has_previous %}
                  <li><a href="?page={{objects.previous_page_number}}">&lt;&lt;</a></li>
                {% endif %}
                {% for num in objects.paginator.page_range %}
                  {% if num == objects.number %}
                    <li class="active"><span>{{num}}</span></li>
                  {% elif num > objects.number|add:'-3' and num < objects.number|add:'3' %}
                    <li><a href="{% url 'main:page' category.id num %}">{{num}}</a></li>
                  {% endif %}
                {% endfor %}
                {% if objects.has_next %}
                <li><a href="?page={{ objects.next_page_number }}">&gt;&gt;</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
    {% endif %}
  </div>
</section>
<section class="ftco-section bg-light">
  <div class="container">
    <div class="row justify-content-center pb-5 mb-3">
      {% autoescape off %}
      {{category.description}}
      {% endautoescape %}
    </div>
  </div>
</section>


{% endblock %}

templates/main/page.html
{% extends "main/base.html" %}
{% load static %}
{% load thumbnail %}
{% block title %}{{page.title}}{% endblock %}
{% block meta_description %}{{page.meta_description}}{% endblock %}
{% block og_title %}{{page.title}}{% endblock %}
{% block site_name %}{{page.title}}{% endblock %}
{% block base_url %}{{base_url}}{% endblock %}
{% block og_logo %}{{base_url}}static/logo.png{% endblock %}
{% block og_description %}{{page.meta_description}}{% endblock %}
{% block content %}

		<section>
			<div class="container">
				<div class="row no-gutters">
				<p class="description">Опис</p>
				{% autoescape off %}
					{{page.description}}
				{% endautoescape %}
				</div>
			</div>
		</section>

{% endblock %}
{% block js %}
{% endblock %}